services:
  php-apache:
    image: cjpjxjx/php-apache:latest
    container_name: php-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./html:/var/www/html
